define audio.main_menu_music = "music/JTiKey_-_lightdrop.ogg"
define audio.streets_of_hell = "music/Gregoire_Lourme_-_City_of_Crime.ogg"
define audio.escape = "music/15_-_Epic_Soul_Factory_-_Honor.ogg"
define audio.first_encounter = "music/Gregoire_Lourme_-_Surrendering_The_Castle_.ogg"
define audio.suffering = "music/Gregoire_Lourme_-_Fate.ogg"
define audio.goblin_chase = "music/08 - Epic Soul Factory - Night Hunter _guitars by PeerGynt Lobogris_.ogg"
define audio.enter_the_ogre = "music/05 - Epic Soul Factory - AMAZONA.ogg"
define audio.die_with_honor = "music/Gregoire_Lourme_-_Swords_of_Fire.ogg"
define audio.after_the_battle = "music/11 - Epic Soul Factory - Moonlit Night.ogg"
define audio.within_reach = "music/Gregoire_Lourme_-_My_Home__My_Family.ogg"
define audio.city_of_smiles = "music/Avel_Glas_-_My_Lodging_s_On_The_Cold_Ground___Kesh_Jig.ogg"
define audio.falling_in_love = "music/09 - Epic Soul Factory - Love.ogg"
define audio.healing_begins = "music/ANtarcticbreeze_-_Life_My_Life_-_Inspirational_Music.ogg"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
