init -2 python:
    gui.init(1920, 1080)
define -2 gui.accent_color = '#000000'
define -2 gui.idle_color = '#56544c'
define -2 gui.idle_small_color = '#888888'
define -2 gui.hover_color = '#ded9c4'
define -2 gui.selected_color = '#a8a184'
define -2 gui.insensitive_color = '#aaaaaa7f'
define -2 gui.muted_color = '#666666'
define -2 gui.hover_muted_color = '#999999'
define -2 gui.text_color = '#ded9c4'
define -2 gui.interface_text_color = '#404040'
define -2 gui.default_font = "gui/CormorantInfant-Medium.ttf"
define -2 gui.name_font = "gui/CormorantInfant-Medium.ttf"
define -2 gui.interface_font = "gui/CormorantInfant-Medium.ttf"
define -2 gui.text_size = 39
define -2 gui.name_text_size = 45
define -2 gui.interface_text_size = 36
define -2 gui.label_text_size = 42
define -2 gui.notify_text_size = 24
define -2 gui.title_text_size = 75
define -2 gui.main_menu_background = "gui/main_menu.jpg"
define -2 gui.game_menu_background = "gui/game_menu.webp"
define -2 gui.show_name = True
define -2 gui.textbox_height = 278
define -2 gui.textbox_yalign = 1.0
define -2 gui.name_xpos = 360
define -2 gui.name_ypos = 0
define -2 gui.name_xalign = 0.0
define -2 gui.namebox_width = None
define -2 gui.namebox_height = None
define -2 gui.namebox_borders = Borders(5, 5, 5, 5)
define -2 gui.namebox_tile = False
define -2 gui.text_xpos = 540
define -2 gui.text_ypos = 63
define -2 gui.side_sprite_xalign = 0.08
define -2 gui.text_width = 1100
define -2 gui.text_xalign = 0.0
define -2 gui.button_width = None
define -2 gui.button_height = 54
define -2 gui.button_borders = Borders(6, 6, 6, 6)
define -2 gui.button_tile = False
define -2 gui.button_text_font = gui.interface_font
define -2 gui.button_text_size = gui.interface_text_size
define -2 gui.button_text_idle_color = gui.idle_color
define -2 gui.button_text_hover_color = gui.hover_color
define -2 gui.button_text_selected_color = gui.selected_color
define -2 gui.button_text_insensitive_color = gui.insensitive_color
define -2 gui.button_text_xalign = 0.0
define -2 gui.radio_button_borders = Borders(38, 6, 6, 6)
define -2 gui.check_button_borders = Borders(38, 6, 6, 6)
define -2 gui.confirm_button_text_xalign = 0.5
define -2 gui.page_button_borders = Borders(15, 6, 15, 6)
define -2 gui.quick_button_borders = Borders(15, 6, 15, 0)
define -2 gui.quick_button_text_size = 21
define -2 gui.quick_button_text_idle_color = gui.idle_small_color
define -2 gui.quick_button_text_selected_color = gui.accent_color
define -2 gui.choice_button_width = 1185
define -2 gui.choice_button_height = None
define -2 gui.choice_button_tile = False
define -2 gui.choice_button_borders = Borders(150, 8, 150, 8)
define -2 gui.choice_button_text_font = gui.default_font
define -2 gui.choice_button_text_size = gui.text_size
define -2 gui.choice_button_text_xalign = 0.5
define -2 gui.choice_button_text_idle_color = "#cccccc"
define -2 gui.choice_button_text_hover_color = "#ffffff"
define -2 gui.slot_button_width = 414
define -2 gui.slot_button_height = 309
define -2 gui.slot_button_borders = Borders(15, 15, 15, 15)
define -2 gui.slot_button_text_size = 21
define -2 gui.slot_button_text_xalign = 0.5
define -2 gui.slot_button_text_idle_color = gui.idle_small_color
define -2 config.thumbnail_width = 288
define -2 config.thumbnail_height = 162
define -2 gui.file_slot_cols = 3
define -2 gui.file_slot_rows = 2
define -2 gui.navigation_xpos = 60
define -2 gui.skip_ypos = 15
define -2 gui.notify_ypos = 68
define -2 gui.choice_spacing = 33
define -2 gui.navigation_spacing = 6
define -2 gui.pref_spacing = 15
define -2 gui.pref_button_spacing = 0
define -2 gui.page_spacing = 0
define -2 gui.slot_spacing = 15
define -2 gui.frame_borders = Borders(6, 6, 6, 6)
define -2 gui.confirm_frame_borders = Borders(60, 60, 60, 60)
define -2 gui.skip_frame_borders = Borders(24, 8, 75, 8)
define -2 gui.notify_frame_borders = Borders(24, 8, 60, 8)
define -2 gui.frame_tile = False
define -2 gui.bar_size = 54
define -2 gui.scrollbar_size = 18
define -2 gui.slider_size = 45
define -2 gui.bar_tile = False
define -2 gui.scrollbar_tile = False
define -2 gui.slider_tile = False
define -2 gui.bar_borders = Borders(6, 6, 6, 6)
define -2 gui.scrollbar_borders = Borders(6, 6, 6, 6)
define -2 gui.slider_borders = Borders(6, 6, 6, 6)
define -2 gui.vbar_borders = Borders(6, 6, 6, 6)
define -2 gui.vscrollbar_borders = Borders(6, 6, 6, 6)
define -2 gui.vslider_borders = Borders(6, 6, 6, 6)
define -2 gui.unscrollable = "hide"
define -2 config.history_length = 250
define -2 gui.history_height = 210
define -2 gui.history_name_xpos = 150
define -2 gui.history_name_ypos = 0
define -2 gui.history_name_width = 225
define -2 gui.history_name_xalign = 1.0
define -2 gui.history_text_xpos = 255
define -2 gui.history_text_ypos = 8
define -2 gui.history_text_width = 1110
define -2 gui.history_text_xalign = 0.0
define -2 gui.nvl_borders = Borders(0, 15, 0, 30)
define -2 gui.nvl_height = 173
define -2 gui.nvl_spacing = 15
define -2 gui.nvl_name_xpos = 645
define -2 gui.nvl_name_ypos = 0
define -2 gui.nvl_name_width = 225
define -2 gui.nvl_name_xalign = 1.0
define -2 gui.nvl_text_xpos = 675
define -2 gui.nvl_text_ypos = 12
define -2 gui.nvl_text_width = 885
define -2 gui.nvl_text_xalign = 0.0
define -2 gui.nvl_thought_xpos = 360
define -2 gui.nvl_thought_ypos = 0
define -2 gui.nvl_thought_width = 1170
define -2 gui.nvl_thought_xalign = 0.0
define -2 gui.nvl_button_xpos = 675
define -2 gui.nvl_button_xalign = 0.0
init -2 python:
    if renpy.variant("touch"):
        gui.quick_button_borders = Borders(90, 21, 90, 0)
    if renpy.variant("small"):
        gui.text_size = 45
        gui.name_text_size = 54
        gui.notify_text_size = 38
        gui.interface_text_size = 54
        gui.button_text_size = 51
        gui.label_text_size = 54
        gui.textbox_height = 360
        gui.name_xpos = 120
        gui.text_xpos = 500
        gui.text_width = 1400
        gui.choice_button_width = 1860
        gui.navigation_spacing = 30
        gui.pref_button_spacing = 15
        gui.history_height = 285
        gui.history_text_width = 1035
        gui.file_slot_cols = 2
        gui.file_slot_rows = 2
        gui.nvl_height = 255
        gui.nvl_name_width = 458
        gui.nvl_name_xpos = 488
        gui.nvl_text_width = 1373
        gui.nvl_text_xpos = 518
        gui.nvl_text_ypos = 8
        gui.nvl_thought_width = 1860
        gui.nvl_thought_xpos = 30
        gui.nvl_button_width = 1860
        gui.nvl_button_xpos = 30
        gui.quick_button_text_size = 30
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
